### ISSUE TITLE
Handling Updates in line with OpenQuake GMPE Library Refactoring

### ISSUE THREAD

**Issue by g-weatherill** [GNS-Science/oq-engine#11]
As mentioned in https://github.com/GNS-Science/oq-engine/pull/10, the GEM OQ-engine is undergoing a massive refactoring of the GMPE library, bringing it out of sync with the current GNS fork. Unfortunately most of the open pull requests contain implementations of, or modifications to, GMPEs, which makes reconciling these changes tricky. This will make the management quite complex and my recommendation is to close most of the open pull requests. Some of these features could go into the main GEM oq-engine code, while others might need to be re-opened after refactoring locally.

My proposed action plan is as follows:

- [ ]  Remove and untrack the Si et al. (2020) and Kuehn et al. (2020) GMPEs from the main library to be able to close https://github.com/GNS-Science/oq-engine/pull/10

- [ ] I have already refactored Si et al. (2020) locally according to the new format  and have the corresponding test tables. So if these pass OK then I will open up a pull request for these in the main OQ-engine. Pull request opened here (https://github.com/gem/oq-engine/pull/6971)

- [ ] As far as I can tell, the addition of the configurable breakpoints for some subduction GMPEs that was opened in https://github.com/GNS-Science/oq-engine/pull/7/files could also go into the main OQ-engine (the default behaviour would correspond to the current implementations

- [ ] Close https://github.com/GNS-Science/oq-engine/pull/6 

- [ ] Refactor https://github.com/GNS-Science/oq-engine/pull/8 offline then close this MR. This version of the model removes the backarc scaling terms for some of the regionalised GMPEs, which means that they could go into the main OQ engine as they are without the need for the additional distance terms. I would like to proceed in this direction if possible as I understand that the specific backarc issues are not being considered right now for New Zealand. Once ongoing work to implement the new distance terms is completed then this can be opened up in a new MR here or in the main oq-engine.

@chrisbc @ElenaManea @nikuehn @thingbaijam @sbSHA - If you have any comments/suggestions then let me know.

FYI @mmpagani - just to let you know what might be coming to the main OQ-engine!

**Comment by thingbaijam** [comment]
A thumbs up for the  addition of the configurable breakpoints for some subduction GMPEs. Thanks!  It would have good if Hassani and Atkinson (2020) were also amenable. But, it seems: scheme of that GM differs from the others in the way of how configurable breakpoints could been implemented.
